# permissions for end users to edit apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-editor-role
rules:
- apiGroups:
  - github.apps.openshift.io
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.apps.openshift.io
  resources:
  - apps/status
  verbs:
  - get
